### ISSUE TITLE
Should this library check for `document.startViewTransition` before doing anything else?

### ISSUE THREAD

**Issue by oscard0m** [paoloricciuti/sveltekit-view-transition#31]
https://github.com/paoloricciuti/sveltekit-view-transition/blob/c04966d1b0555e05e267b300e81ba79628bf16fd/src/lib/sveltekit-view-transition.ts#L337-L340

**Comment by paoloricciuti** [comment]
Mmm it might be a good idea...I'm trying to think if there's a downside to it but I can't seem to find one...I'll let the night bright my reason and eventually fix that tomorrow

**Comment by paoloricciuti** [comment]
Closed by #32
