### ISSUE TITLE
It can improve?

### ISSUE THREAD

**Issue by NelsonDJCR** [paoloricciuti/sveltekit-view-transition#36]
### Describe the problem

**Install pwa**

Is it very complicated to add the service to make it work as a PWA? It is something that I have not been able to achieve and I would like it to handle view transitions

by the way, your project helped me a lot, thanks for sharing it. ty so much

### Describe the proposed solution

I'm sure it would help many people and me 😞

**Comment by paoloricciuti** [comment]
> ### Describe the problem
> **Install pwa**
> 
> Is it very complicated to add the service to make it work as a PWA? It is something that I have not been able to achieve and I would like it to handle view transitions
> 
> by the way, your project helped me a lot, thanks for sharing it. ty so much
> 
> ### Describe the proposed solution
> I'm sure it would help many people and me 😞

Make a project work as a PWA is completely unrelated to the view transition API tho...there are plenty of examples out there on how to turn your project in an installable PWA but I don't feel like this library should be mixed with that.

Closing right now but feel free to open it again if I misinterpreted your issue :)
