### ISSUE TITLE
[INQUIRY]: Can view transitions play WITHIN the page? (without navigations)

### ISSUE THREAD

**Issue by Bewinxed** [paoloricciuti/sveltekit-view-transition#39]
### Describe the problem

I am trying to animate between a view/hidden state from an on-page image to a larger image in the modal.

I am putting the same view transition name on both containers using the "use" directive, with the exact same ID.

However, the animation does not play or crossfade between the two elements, I have tried to put the modal content within a new subpage (using ID routes and the parent page as a layout) but no go.

I have questions because I can't find answers for these online:

- Can view transitions transition between two elements with the same view-transition-name WITHOUT having to destroy the original element?
- Can view transitions transition between different states within the same page/component WITHOUT having to navigate?

Thank you so much!

### Describe the proposed solution

Just an inquiry.

**Comment by paoloricciuti** [comment]
Hi, view transition api can actually do this but it's simple enough that it's not the scope of this library...what you need to do is just
```ts
document.startViewTransition(()=>{
// update your state
});
```
In css set the `view-transition-name` on the element that you want to animate. Consider that when the transition start and when it end only one element needs to have that specific view transition name.
