### ISSUE TITLE
Update for SvelteKit 2?

### ISSUE THREAD

**Issue by enisbu** [paoloricciuti/sveltekit-view-transition#40]
### Describe the problem

Thank you for this awesome library!

### Describe the proposed solution

Is it possible to update the dependencies for the newest SvelteKit 2 version? Would really appreciate it !:)

**Comment by paoloricciuti** [comment]
Oh totally, completely forgot about this. Give me a minute

**Comment by paoloricciuti** [comment]
Updated on v0.5.3

**Comment by enisbu** [comment]
wow that was fast, thank you so much! :)
